name: Debug Auto-update

on:
  workflow_dispatch: # Manual triggering only
  push:
    paths:
      - ".github/workflows/debug-auto-update.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  debug-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests packaging

      - name: Debug environment
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"

      - name: Test PyPI connection
        run: |
          python3 -c "
          import requests
          try:
              response = requests.get('https://pypi.org/pypi/gatenet/json', timeout=30)
              response.raise_for_status()
              data = response.json()
              print(f'Latest gatenet version: {data[\"info\"][\"version\"]}')
          except Exception as e:
              print(f'Error: {e}')
          "

      - name: Check current formula
        run: |
          echo "Current gatenet formula:"
          cat Formula/gatenet.rb | head -10

      - name: Test update detection
        run: |
          python3 scripts/update-formulas-minimal.py
