name: Simple Auto-update Test

on:
  workflow_dispatch: # Manual triggering
  schedule:
    - cron: "*/30 * * * *" # Every 30 minutes for testing

permissions:
  contents: write
  pull-requests: write

jobs:
  test-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for gatenet updates
        id: check_gatenet
        run: |
          echo "Checking gatenet updates..."

          # Get current version from formula
          current=$(grep -o 'gatenet-[0-9]\+\.[0-9]\+\.[0-9]\+' Formula/gatenet.rb | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
          echo "Current version: $current"

          # Get latest version from PyPI
          latest=$(curl -s https://pypi.org/pypi/gatenet/json | grep -o '"version":"[^"]*"' | cut -d'"' -f4)
          echo "Latest version: $latest"

          if [ "$current" != "$latest" ]; then
            echo "Update needed: $current -> $latest"
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "current_version=$current" >> $GITHUB_OUTPUT
            echo "latest_version=$latest" >> $GITHUB_OUTPUT
          else
            echo "No update needed"
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create simple PR
        if: steps.check_gatenet.outputs.update_needed == 'true'
        run: |
          echo "Would create PR to update gatenet from ${{ steps.check_gatenet.outputs.current_version }} to ${{ steps.check_gatenet.outputs.latest_version }}"
